EmurgoHK/cardanoupdate

- README.md
Solution: Update readme with information relevant to cardanupdate repo.
> Problem: Readme was forked from Emurgis and is not up to date (#1)

- .meteor/packages
- .meteor/versions
- imports/api/news/methods.js
- imports/api/news/methods.test.js
- imports/api/news/news.js
- imports/api/news/server/publications.js
- imports/api/user/server/publications.js
- imports/startup/client/index.js
- imports/startup/client/routes.js
- imports/startup/server/register-api.js
- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/news/newsForm.html
- imports/ui/pages/news/newsForm.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
- imports/ui/shared/empty-result/empty-result.html
- imports/ui/shared/empty-result/empty-result.js
- imports/ui/shared/empty-result/empty-result.scss
- imports/ui/shared/loader/loader.html
- imports/ui/shared/loader/loader.js
- imports/ui/shared/loader/loader.scss
- package-lock.json
- package.json
Solution: Allow logged in users to add/edit/remove/view news items. News item consists of a headline (140 chars max), summary (500 chars max) and body.
> Problem: Cannot add news items (#7)

- .meteor/packages
- imports/api/comments/comments.js
- imports/api/comments/methods.js
- imports/api/comments/methods.test.js
- imports/api/comments/server/publications.js
- imports/api/news/methods.js
- imports/startup/server/register-api.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
- package-lock.json
- package.json
Solution: Allow logged in users to comment on news items.
> Problem: Users can't comment on news items (#9)

- AUTHORS
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/home/home.scss
- imports/ui/pages/news/news.ui-test.js
Solution : UI-UX updated, table replaced with cards
>  Problem : News list UX is not good #12

- imports/api/comments/methods.js
- imports/api/news/methods.js
- imports/api/news/methods.test.js
- imports/api/notifications/methods.js
- imports/api/notifications/methods.test.js
- imports/api/notifications/notifications.js
- imports/api/notifications/server/publications.js
- imports/startup/client/index.js
- imports/startup/client/routes.js
- imports/startup/client/testing.js
- imports/startup/server/register-api.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
- imports/ui/pages/notifications/notifications.html
- imports/ui/pages/notifications/notifications.js
- imports/ui/pages/notifications/notifications.ui-test.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution: Implement a simple notifications system and send notifications for comments received on news (for authors & users who have comments). Let users unsubscribe from a news article if they don't want to receive notifications. Write appropriate client side and server side tests.
> Problem: No user notifications (#16)

- .meteor/packages
- .meteor/versions
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
Problem: news times are absolute #21 
Solution : Momentjs used for change in time format
Problem : User id instead of user name on news #23 
Solution : User Name added instead of user Id, also check for profile exist or not
>  Problem: news times are absolute #21 and authors id instead of name #23

- imports/api/comments/methods.js
- imports/api/comments/methods.test.js
- imports/api/comments/server/publications.js
- imports/api/news/methods.js
- imports/api/news/methods.test.js
- imports/api/news/server/publications.js
- imports/startup/client/routes.js
- imports/ui/pages/home/home.html
- imports/ui/pages/moderator/flagged/flaggedItems.html
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/pages/moderator/flagged/flaggedItems.ut-test.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
- imports/ui/shared/sidebar/sidebar.html
Solution: Allow users to flag news items and comments, and allow moderators to see flagged items and decide whether to keep them or remove them.
> Problem: Users can't flag spam or abusive content (#11)

- imports/api/comments/methods.js
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/pages/news/viewNews.js
Solution: Update the codebase to reflect new changes.
> Problem: Wrong username used in codebase (#26)

- imports/api/news/methods.js
- imports/api/news/methods.test.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/login/login.ui-test.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/signup/signup.ui-test.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.ui-test.js
Solution: Let users upvote or downvote news articles, and let them sort articles by time or by rating.
> Problem: Users can't upvote or downvote news articles. (#28)

- .gitignore
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/header/header.scss
- imports/ui/shared/header/header.ui-test.js
Solution : Responsive issues fixed by CSS
home page link added to home
Nav bar links colors updated for better visibility
>  Problem : Top Navbar broken and bad UX #30

- imports/api/comments/methods.js
- imports/api/news/methods.js
- imports/api/user/methods.js
- imports/api/user/methods.test.js
- imports/api/user/server/publications.js
- imports/startup/client/routes.js
- imports/ui/pages/moderator/flagged/flaggedItems.ut-test.js
- imports/ui/pages/moderator/pardon/pardon.html
- imports/ui/pages/moderator/pardon/pardon.js
- imports/ui/pages/moderator/pardon/pardon.ui-test.js
- imports/ui/pages/moderator/pardon/pardonUser.html
- imports/ui/pages/moderator/pardon/pardonUser.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/suspended/suspended.html
- imports/ui/pages/suspended/suspended.js
- imports/ui/shared/sidebar/sidebar.html
Solution: Recycle parts of Blockrazor's strike based suspension system and implement it here. Add appropriate client side and server side tests.
> Problem: No way to suspend users who post spam or abusive content (#31)

- .meteor/packages
- .meteor/versions
- imports/ui/pages/news/news.scss
- imports/ui/pages/news/newsForm.html
- imports/ui/pages/news/newsForm.js
Solution : Markdown editor added
If tests are broken, I'll try to fix in the same PR and for UI-UX, I'll send another PR.
> Problem : No rich text editors in news #15

- imports/ui/pages/news/news.scss
- imports/ui/pages/news/newsForm.html
- imports/ui/pages/news/newsForm.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
>  Problem : News bad UI-UX #35

- imports/ui/pages/news/news.ui-test.js
Solution: Fix failing client side tests.
> Problem: Tests are failing.

- imports/api/user/methods.js
- imports/startup/client/routes.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/userProfile/editProfile.html
- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/userProfile.scss
- imports/ui/pages/userProfile/viewProfile.html
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution :
Edit profile added
Bio added on user profile
Link to author's profile added on news
Edit profile link added on navigation
>  Problem : User can't know about author #38 

- imports/api/comments/methods.js
- imports/api/comments/methods.test.js
- imports/api/comments/server/publications.js
- imports/api/news/methods.js
- imports/ui/pages/news/commentBody.html
- imports/ui/pages/news/commentBody.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
Solution: Modify the commenting system to support nested comments.
> Problem: Comment replies are not working (#43)

- imports/api/projects/methods.js
- imports/api/projects/projects.js
- imports/api/projects/server/publications.js
- imports/startup/client/routes.js
- imports/startup/server/register-api.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/shared/sidebar/sidebar.html
- package-lock.json
solution: added ability for user to add. edit and delete projects. included projects link in sidebar
> problem: cannot add cardano related projects #19

- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
Solution : GitHub repo link added to side and top navigation
> Problem: no prominent link to github repo #47

- imports/ui/shared/header/header.scss
Solution : New font added for logo
_PS : I didn't added `font-weight` to css, because we are only importing font with 700 weight only._
> Problem: cardano logo not used #56

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
Solution: Adds number of comments for each news by updating comments helper in home.js
> problem: number of comments not shown #46

- .meteor/packages
- .meteor/versions
- imports/ui/pages/login/login.html
- imports/ui/pages/login/login.js
- imports/ui/pages/login/login.ui-test.js
Solution: Add sign up/in using oauth tokens from popular third party services (facebook, google, github)
> Problem: Sign up can be annoying (#50)

- imports/ui/pages/home/home.html
solution: moved news meta to bottom of card. moved star rating to the right. reduced padding of card and parent element. using carets for up/down rating filter. Got rid of extra padding in filter
> problem: display tiles are larger than needed #52

- imports/ui/pages/home/home.html
- imports/ui/pages/news/commentBody.html
- imports/ui/pages/news/viewNews.html
- imports/ui/stylesheets/_custom.scss
solution: applied a class of card-image-top to news images. some UI adjustments to the news item view
> problem: bad UI-UX on news image #66

- AUTHORS
- imports/ui/pages/home/home.html
Add tagline and title as h1 and h4 tags in home html
> #71 problem: missing tagline and title in home page

- imports/ui/pages/home/home.html
Solution : Sorting by negative rating removed
> Problem: sort by negative rating is't needed #72

- imports/api/comments/methods.js
- imports/api/comments/methods.test.js
- imports/api/comments/server/publications.js
- imports/api/projects/methods.js
- imports/api/projects/methods.test.js
- imports/startup/client/routes.js
- imports/ui/pages/comments/commentBody.html
- imports/ui/pages/comments/commentBody.js
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/news/viewNews.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.ui-test.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
Solution: Add a new page where users can view project details and comment. Allow users to comment with "Cool stuff" and "Red flags" by reusing the current comments backend, so it supports nested comments out of the box. Cover everything with appropriate client-side and server-side tests.
> Problem: Cannot comment on projects (#70)

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution : Onclick toggleclass fixed
> Problem: side menu doesn't work on mobile #51

- .gitignore
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
Solution : UI-UX updated for home and CSS added to render images in same aspect ratio
> Problem: layout with images is clunky #68

- imports/ui/pages/home/home.html
- imports/ui/shared/header/header.html
Solution : Add news link removed from top navigation and added to added to home page
> Problem : Top navigation bad UI-UX in mobile #79

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
Solution : Projects link added on top nav
> Problem : Hard to find projects for readers #81

- client/head.html
- imports/api/projects/methods.js
- imports/ui/pages/projects/projectForm.js
- imports/ui/stylesheets/bundle.scss
solution: made github url optional. moved Montserrat font import to header
> problem: not all projects will have a github repo #69

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/home/home.scss
- package-lock.json
- package.json
Solution : UI-UX updated for home page, cards layout updated for news item, Projects added on home page
Fixes #82 and #84
>  Problem : Home page bad UI-UX #84, #82

- imports/ui/layouts/body/body.html
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/home/home.scss
- imports/ui/pages/news/newsForm.html
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/notifications/notifications.html
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/viewProject.html
- imports/ui/stylesheets/_custom.scss
Solution: Reverted back to a row layout. UI improvements to news cards. Styled homepage tagline/header. Improved news card responsiveness
> Problem: new homepage layout causing UI inconsistency #90

- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
Solution: Adds a waring icon with a modal for projects without a source link
> problem: projects without github repo can be dangerous #94

- imports/api/news/methods.js
- imports/api/projects/methods.js
- imports/ui/pages/news/newsForm.html
- imports/ui/pages/news/newsForm.js
- imports/ui/pages/news/viewNews.html
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/viewProject.html
Solution: Implements tags users can now add custom tags to the project & news
> problem: cannot find news or projects by type #92

- imports/startup/client/routes.js
Solution: user can visit projects page without log in
> problem: users have to log in to see projects #97

- .meteor/packages
- imports/api/projects/methods.js
- imports/api/projects/methods.test.js
- imports/startup/client/routes.js
- imports/startup/client/testing.js
- imports/ui/pages/moderator/changes/changes.html
- imports/ui/pages/moderator/changes/changes.js
- imports/ui/pages/moderator/changes/changes.ui-test.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/pages/projects/projects.ui-test.js
- imports/ui/shared/sidebar/sidebar.html
Solution: Implement a basic system where users can contribute data points and these changes can be 'merged' by maintainers. Add appropriate client side and server side tests.
> Problem: Users cannot add a github repo to projects (#95)

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
Solution: Adds a search bar on projects & news page where user can search by tags, headline & summary
> problem: users cannot search news & projects #100

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
solution: Adds link to the profile of user on home page
> problem: contributor profile is not visible #109

- imports/api/news/methods.js
- imports/api/news/methods.test.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/news/news.ui-test.js
- package-lock.json
solution: implemented a thumbs up/down voting system. allowing users to votes up/down. updated vote metrics where `rating = (upvotes - downvotes) / total number of votes` and sorting votes by most popular based on this. Updated unit and ui tests
> problem: cannot change vote after voting #54

- imports/startup/client/index.js
- imports/startup/client/routes.js
- imports/ui/layouts/body/body.js
- imports/ui/shared/header/header.ui-test.js
Solution: All actions that require a user to be logged in are be displayed to logged out users as well, but they're redirected to the login page onclick.
> Problem: Not enough encouragement for users to add new data (#102)

- imports/api/events/events.js
- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/api/events/server/publications.js
- imports/startup/client/routes.js
- imports/startup/server/register-api.js
- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/events/viewEvent.js
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
Solution : Add, edit, delete, flag, watch/unwatch event added
**_PS : I don't usually work on backend, please review if this is good enough for merge. I'll work on tests on another PR, if failed._**
> Problem: users cannot add events #93

- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/events/viewEvent.html
solution: add an "RSVP instructions" field to the new event creation form
> #132 Problem: easy to forget to add RSVP info to events

- imports/api/events/methods.js
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.scss
- imports/ui/pages/events/viewEvent.html
Solution : Markdown editor added for event description and max char increased to 1000
> Problem: Event description can't be formatted #130

- imports/ui/layouts/body/body.html
- imports/ui/layouts/body/body.scss
Solution: on mobile, replaced the tagline in the header with links to news, projects and event pages.
> Problem: users might miss sections on mobile #134

- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/api/news/methods.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/moderator/flagged/flaggedItems.ui-test.js
- imports/ui/pages/moderator/pardon/pardon.ui-test.js
- imports/ui/pages/news/news.ui-test.js
- imports/ui/pages/projects/projects.ui-test.js
Solution: Fix client side and server side tests. Fix lots of functionality problems.
> Problem: Tests are failing (#142)

- .gitignore
- .meteor/packages
- .meteor/versions
- imports/startup/client/routes.js
- imports/ui/pages/login/login.html
- imports/ui/pages/login/login.js
Solution : Forgot password form added, password reset link added on login page and email setup for sending emails
Add this on .env file on root directory
`MAIL_URL=smtp://user:pass@smtp.sendgrid.net:587`
**Login details:**
user : blockrazor
pass : blockrazor125
> Problem : User can't reset password #145

- imports/startup/client/config.js
- imports/ui/shared/header/header.js
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
solution: toggling sidebar-show class when body is clicked on smaller devices.  fixed icon on research-papers sidebar menu. presrving default behavior when sidebar links are clicked
> problem: side menu is annoying on small screens #110

- imports/ui/shared/uploader/uploader.js
Solution: Trim data before sending it to the server to ensure that md5s match every time.
> Problem: Error when uploading research papers (#158)

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/userProfile/viewProfile.html
- imports/ui/stylesheets/_custom.scss
solution: displaying user image in profile. using gravatar as default pic if profile picture does not exist. updated activity UI
> problem: user profile page does not show existing profile picture #108

- imports/api/projects/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/stylesheets/_custom.scss
solution: add dynamic list of Social Resources in project form
> problem: cannot add social resources #159

- imports/api/user/server/publications.js
- imports/ui/pages/comments/commentBody.html
- imports/ui/pages/comments/commentBody.js
- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/viewProfile.html
solution: now showing image of profile's owner instead of current user
> problem: profile page shows image of current user #165

- imports/api/projects/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/stylesheets/_custom.scss
solution: revert commit made in #159
> problem: #159 does not solve any problems

- imports/ui/pages/userProfile/editProfile.html
- imports/ui/shared/uploader/uploader.html
solution: updated edit profile page UI
> problem: edit profile page out of style #164

- imports/ui/pages/events/eventForm.js
- imports/ui/pages/news/newsForm.js
- imports/ui/pages/research/research.ui-test.js
- imports/ui/shared/uploader/uploader.html
- imports/ui/shared/uploader/uploader.js
- imports/ui/shared/uploader/uploader.ui-test.js
Solution: Create a custom insert image button in the simplemde toolbar which shows an image upload form in a modal and lets users insert the uploaded image. Modify the current upload system to support multiple uploader instances on one view.
> Problem: Picture insert button inserts http link (#169)

- .meteor/packages
- .meteor/versions
- imports/api/user/methods.js
- imports/api/user/server/publications.js
- imports/api/user/server/startup.js
- imports/api/user/users.js
- imports/api/user/usersStats.js
- imports/startup/server/register-api.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
Solution : User stats added to home page
> Problem: can't see user statistics #146

- imports/startup/client/routes.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
- imports/ui/pages/news/news.html
- imports/ui/pages/news/news.js
- imports/ui/pages/news/news.scss
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
Solution : Projects and Events added along with news on home page,navigation links updated
>  Problem: home route only shows news #160

- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/news/news.ui-test.js
Solution: Fix failing client side tests.
> Problem: Tests are failing

- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.js
- imports/ui/pages/events/events.scss
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- package-lock.json
Solution : Upcoming, Ongoing and Past events tag added on events summary card,
View all link updated and only upcoming and ongoing events are displaying on home page
>  Problem : Events are not labelled #183

- imports/api/user/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/projects.scss
- package-lock.json
- package.json
Solution : Modal and on focus content added for instruction on project form
> Problem: contributors miscatagorize things #171

- imports/startup/client/index.js
- imports/startup/client/routes.js
- imports/ui/shared/uploader/uploader.ui-test.js
Solution: Fixing failing client side tests.
> Problem: Tests are failing. (#201)

- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/viewProfile.html
Solution: Adds different sections for project, research paper & comments on profile page
> Problem: user profile section is unorganised #195

- imports/ui/pages/home/home.html
- package-lock.json
solution: applied a class of h6 to the card text
> problem: site stats cards text too large #205

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/research/research.js
Solution: Improved the UI of the homepage by adding consistent design throughout the app.
Design :
> Problem : bad UI/UX on home route #200

- imports/api/projects/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
solution: revert commit a6e1703a55e852b702f18d32f17e59dbfb59433b, reversing
changes made to cf33256900c8b87a3cce9ddd900e42597d267e42.
> problem: #197 breaks many things

- imports/api/learn/learn.js
- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/api/learn/server/publications.js
- imports/startup/client/routes.js
- imports/startup/server/register-api.js
- imports/ui/pages/addNewModal/addNewModal.html
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/learn/learn.html
- imports/ui/pages/learn/learn.js
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
Solution: Add a Learn section which is similar to other existing sections. Add the appropriate client side and server side tests.
> Problem: No Learn section (#217)

- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
solution: add limit characters function
>  problem: content boxes have different sizes #221 

- imports/ui/pages/events/events.scss
Solution: Change the grey background to a white one.
> Problem: Greyed out title fields can be confusing to users (#228)

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/community/socialResources.html
- imports/ui/pages/home/home.html
- imports/ui/pages/research/research.html
solution: create global function LimitChars and use it to Home & community & research
> problem: content boxes have different sizes #221

- imports/ui/pages/events/eventForm.js
- imports/ui/pages/learn/learnForm.js
- imports/ui/shared/uploader/uploader.js
Solution: Add a 'embed video' button to the SimpleMDE editor toolbar which presents users with a modal where they can enter the YouTube video link and insert it automagically.
> Problem: Not easy to embed youtube videos in "learn" content (#234)

- imports/api/user/server/publications.js
- imports/ui/pages/projects/projectForm.js
Solution: fixed the logic for displaying the modal to the user
> Problem: instruction modal doesn't hide even if user hides it #247

- imports/api/comments/methods.test.js
- imports/api/events/methods.test.js
- imports/api/learn/methods.test.js
- imports/api/news/methods.test.js
- imports/api/notifications/methods.test.js
- imports/api/research/methods.test.js
- imports/api/socialResources/methods.test.js
- imports/api/stats/methods.test.js
- imports/api/warnings/methods.test.js
- imports/ui/pages/moderator/flagged/flaggedItems.ui-test.js
- imports/ui/pages/warnings/warnings.ui-test.js
> Problem: Tests are failing. (#245)

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
Solution : CSS classes fixed and media query added
> Problem : User stats broken on small screen #246

- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/community/viewSocialResource.html
Solution:
Added tags to social resources as an optional property
Updated tests for social resources
Updated UI to enable editing and listing tags on social resources
This is done mostly the same as the tags related code on learning resources.
> problem: no type for social resources #216

- imports/api/tags/methods.js
Solution: changed to increment it with $inc
> Problem: mention incremented non-atomically #256

- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/warnings/warningForm.js
Solution:
Made the button disabling logic more robust
Deduplicating tags by name when saving
> Problem: Users can add the duplicate tags #255

- imports/ui/pages/home/home.ui-test.js
Solution: Add appropriate client-side tests to prevent possible regressions.
> Problem: No client-side tests on the home route (#244)

- imports/ui/pages/home/home.js
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/warnings/viewWarning.js
> Problem: Proposing data for projects error #261

- imports/api/projects/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
Solution: Update the project edit UI to show and to be able to accept/reject changes.
> Problem: Users can't see proposed data changes (#263)

- imports/ui/pages/addNewModal/addNewModal.html
Solution : Text updated in add new modal
> Problem: inconsistent uppercase in add new  #268

- imports/ui/pages/events/events.html
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
- imports/ui/pages/learn/learn.html
- imports/ui/pages/projects/projects.html
- imports/ui/pages/research/research.html
- imports/ui/pages/warnings/warnings.html
Solution : Warning icon replaced with dropdown containing report link
> Problem: flagging button looks dangerous #266

- imports/ui/pages/community/socialResources.html
- imports/ui/pages/community/socialResources.js
- imports/ui/pages/learn/learn.html
- imports/ui/pages/learn/learn.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/pages/research/research.html
- imports/ui/pages/research/research.js
- imports/ui/pages/warnings/warnings.html
- imports/ui/pages/warnings/warnings.js
Solution : not found message added on search if there is no content
> Problem: no info when search has no content #269

- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/ui/pages/learn/learn.html
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/learn/viewLearn.html
Solution : Summary added to learning resources
> Problem: no summary for learning resources #276

- imports/api/events/methods.js
- imports/api/learn/methods.js
- imports/api/projects/methods.js
- imports/api/research/methods.js
- imports/api/socialResources/methods.js
- imports/api/warnings/methods.js
- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/research/researchForm.js
- imports/ui/pages/warnings/warningForm.html
- imports/ui/pages/warnings/warningForm.js
Solution : Text limits updated for title to 90 and for summary to 260
Fixes for #281 & #285
> Problem: Bad limit for title and summary #281 #285

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
- imports/ui/pages/learn/learn.html
Solution : Layout updated accordingly rest of summary cards used in project
> Problem: weird layout on learning page #284

- imports/ui/pages/home/home.js
Solution : Item limit changed to 6 from 5
> Problem: Displayed columns in /home are odd #279

- imports/ui/pages/community/socialResources.html
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/home/home.html
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/warnings.html
Solution : Globe icon is replaced with external link icon and tooltip titiles added on all links
> Problem: not clear what globe icon is for #223

- imports/startup/client/index.js
- imports/startup/client/routes.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/tag/tag.html
- imports/ui/pages/tag/tag.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/learningResourceList/learningResourceList.js
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/projectList/projectList.js
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/socialResourceList/socialResourceList.js
- imports/ui/shared/warningList/warningList.html
- imports/ui/shared/warningList/warningList.js
Solution:
Added a new tags page
Linked tags page where we display tags
Extracted resource type specific lists as sub-components to avoid code duplication - we should later convert to these on other pages too.
> problem: can't search by tag #271

- imports/startup/client/routes.js
- imports/ui/pages/home/home.html
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/warningForm.html
- imports/ui/pages/warnings/warningForm.js
- imports/ui/pages/warnings/warnings.html
- imports/ui/pages/warnings/warnings.js
- imports/ui/pages/warnings/warnings.ui-test.js
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/warningList/warningList.html
Solution : Changed warnings to scams in ui including routes
> Problem: 'warnings' section isn't very clear #277

- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/api/socialResources/server/startup.js
- imports/startup/server/register-api.js
- imports/ui/pages/community/socialResources.html
- imports/ui/pages/community/socialResources.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/socialResourceList/socialResourceList.js
Solution:
Added a resourceUrlType field to social resources. Set during create and edit
Added a cron job to update resourceUrlType hourly. Should be disabled once it's stable.
Updated icons to display
> problem: type of community is not displayed #265

- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
Solution: only displaying one comment area, allowing showing old comments, adding new ones with "warning" type
> Problem: Comment categories are bad on Scams #295

- imports/ui/pages/projects/projectForm.html
Solution : Set max-length attribute.
> Problem: Project name textbox don't have max character length

- AUTHORS
- imports/api/user/users.js
#222 new accounts are not working properly.
> Username not showing when login > Fixed
> View profile, Edit profile working fine now.
> Problem: Username not showing, Solution: add profile in callback

- imports/api/projects/methods.js
Solution: Fix failing client side tests.
> Problem: Tests are failing (#286)

- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/stylesheets/bundle.scss
- package-lock.json
- package.json
Solution : Daterange picker plugin added
> Problem: events date is really annoying #272

- imports/ui/layouts/body/body.html
solution: update tag line to reflect current scope of site
> problem: tag line is no longer accurate

- imports/ui/pages/community/socialResources.html
- imports/ui/pages/events/events.html
- imports/ui/pages/learn/learn.html
- imports/ui/pages/projects/projects.html
- imports/ui/pages/research/research.html
- imports/ui/pages/warnings/warnings.html
Solution : description added on all section
> Problem: no description for each section #313

- imports/ui/pages/community/socialResources.html
- imports/ui/pages/community/socialResources.js
- imports/ui/pages/learn/learn.html
- imports/ui/pages/learn/learn.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/pages/warnings/warnings.html
- imports/ui/pages/warnings/warnings.js
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/warningList/warningList.html
Solution: Moved normal listing/search results to the extracted components too
> Problem: code duplication for lists #302

- imports/ui/layouts/body/body.scss
Solution : Image path changed to absolute instead of relative
> Problem: missing assets in internal pages #331

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/learningResourceList/learningResourceList.js
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/projectList/projectList.js
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/socialResourceList/socialResourceList.js
- imports/ui/shared/warningList/warningList.html
- imports/ui/shared/warningList/warningList.js
Solution:
Updated lists on home to use the common list components
Updated list components to allow for wrapper/custom classes
Updated project list component to not display the warning icon
> problem: missing repo icon inconsistency #312

- imports/ui/pages/events/events.html
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/home/home.html
Solution : RSVP Icon & a tag with link added and Location link added for Google maps
Fixes for #325 & #326
>  Problem: Event RVSP and location link isn't active #325 & #326

- imports/ui/layouts/body/body.html
solution: increase heading size
> problem: heading is too small

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.scss
- imports/ui/pages/home/home.html
solution: Adds easy to parse dates. Fixes edit event issue by adding utc dates instead of js dates
> problem: event dates for upcoming events are hard to parse #317

- imports/ui/pages/home/home.html
solution: change 'active' to 'upcoming'
> problem: upcoming events labelled as active

- imports/api/projects/methods.js
- imports/api/socialResources/methods.js
- imports/api/tags/methods.js
- imports/api/warnings/methods.js
Solution: decrement tags when the resource is deleted
> problem: tag mention doesn't decrease when deleting resources #257

- imports/ui/shared/uploader/uploader.js
problem: users profile pictures are not used, 
Solution: When Image upload same time update database data
> problem: users profile pictures are not used #315

- imports/api/events/server/publications.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/events.js
Solution: Sorts events by start date
> Problem: events are not sorted according to start date #340

- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/pages/research/research.html
- imports/ui/pages/research/research.js
> Problem: No sorting for Project/Research page #327

- imports/ui/shared/learningResourceList/learningResourceList.html
Solution: Fixed component re-adding missing code
> problem: regression caused by #333 #341

- imports/ui/pages/projects/projects.html
- imports/ui/pages/research/research.html
Solution: Added a clearfix div after floating selector
> Problem: sort selector inside the lists #349

- imports/ui/pages/events/events.html
- imports/ui/pages/home/home.html
- imports/ui/pages/research/research.html
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/warningList/warningList.html
> Problem : Report link UI isn't uniform #334

- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.scss
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
- imports/ui/pages/research/research.html
- imports/ui/pages/research/research.js
- imports/ui/pages/research/research.scss
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/learningResourceList/learningResourceList.js
- imports/ui/shared/learningResourceList/learningResourceList.scss
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/projectList/projectList.js
- imports/ui/shared/projectList/projectList.scss
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/socialResourceList/socialResourceList.js
- imports/ui/shared/socialResourceList/socialResourceList.scss
- imports/ui/shared/warningList/warningList.html
- imports/ui/shared/warningList/warningList.js
- imports/ui/shared/warningList/warningList.scss
Solution: 
Added a pre-set height to elements containing variable length text (card-text)
Limited length of text where it was on a card with no limits
> problem: content boxes are not uniform #267

- imports/startup/client/index.js
- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.js
- imports/ui/pages/events/events.scss
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
- imports/ui/pages/home/home.scss
- imports/ui/pages/research/research.html
- imports/ui/pages/research/research.js
- imports/ui/pages/research/research.scss
- imports/ui/shared/eventList/eventList.html
- imports/ui/shared/eventList/eventList.js
- imports/ui/shared/eventList/eventList.scss
- imports/ui/shared/researchList/researchList.html
- imports/ui/shared/researchList/researchList.js
- imports/ui/shared/researchList/researchList.scss
Solution: Extracted common code into a shared component
> Problem: code duplication for lists #359

- imports/api/learn/methods.js
Solution: Raise the limit on max chars for the summary to match projects and warnings
> Problem: Validation-hint conflict for summary #361

- imports/api/socialResources/methods.js
- imports/api/warnings/methods.js
- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/learn/learnForm.js
Solution: Fix failing client side and server side tests and fix bugs and regressions that were causing test failures.
> Problem: Tests are failing (#337)

- imports/ui/pages/events/viewEvent.html
Solution : Follow button added instead of eye icon
> Problem: Confusing usage of 'Eye' icon #323

- imports/ui/pages/home/home.html
Solution : Box UI updated for mobile
> Problem: stats use too much space on mobile #363

- imports/ui/shared/header/header.html
solution: change color of scams menu item and move it to the last item.
> problem: 'scams' looks out of place

- .meteor/packages
- .meteor/versions
- imports/ui/pages/login/login.html
- imports/ui/pages/login/login.js
- imports/ui/pages/login/login.ui-test.js
Solution: removed those from the UI and removed packages
> Problem: GitHub and google login not working #250

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/warnings/warningForm.html
solution: list existing tags for the resource in edit mode
> problem: user cannot remove tags in edit mode #338

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
Solution : add new button moved to top-right of title bar and made it full width on mobile screen
> Problem: add new button is out of place #370

- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
- imports/ui/shared/eventList/eventList.html
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/researchList/researchList.html
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/warningList/warningList.html
Solution: Removes sections from home page & adds label of type to each resource.
Updates the list components & home route
**Home Page UI**
> problem: home route layout isn't great #369

- imports/startup/client/index.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/shared/eventList/eventList.html
- imports/ui/shared/flagItem/flagItem.html
- imports/ui/shared/flagItem/flagItem.js
- imports/ui/shared/flagItem/flagItem.scss
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/researchList/researchList.html
- imports/ui/shared/warningList/warningList.html
Solution : Created common flagItem component to use across site
> Problem: inconsistent flagging/reporting #378

- imports/api/warnings/methods.js
- imports/api/warnings/methods.test.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/warningForm.html
- imports/ui/pages/warnings/warningForm.js
- imports/ui/shared/warningList/warningList.html
solution: removes unnecessary data from scam
> problem: unnecessary data on scam items #374

- imports/startup/client/index.js
- imports/ui/pages/comments/commentBody.html
- imports/ui/pages/comments/commentBody.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/events/viewEvent.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/moderator/candidates/candidates.html
- imports/ui/pages/moderator/changes/changes.html
- imports/ui/pages/moderator/changes/changes.js
- imports/ui/pages/moderator/flagged/flaggedItems.html
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/pages/moderator/pardon/pardonUser.html
- imports/ui/pages/moderator/pardon/pardonUser.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/research/viewResearch.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/shared/userNameDisplay/userNameDisplay.html
- imports/ui/shared/userNameDisplay/userNameDisplay.js
Solution: Extracted a common userNameDisplay component (this will allow as to add other badges later)
> Problem: nothing to distinguish moderator #371

- imports/api/projects/methods.js
- imports/api/research/methods.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/research/researchForm.html
- imports/ui/pages/research/researchForm.js
Solution : Text limit removed from project description and research abstract
> Problem: Limited words count in abstract #373

- imports/ui/pages/home/home.scss
solution: put item type at top of card
> problem: item type is hard to follow

- imports/ui/shared/sidebar/sidebar.html
problem: scam menu item is strange, it shouldn't be mixed in with other 'normal' things.
solution: change font color and icon, move to end of list
> problem: scam menu item is strange

- client/head.html
> problem: incorrect title

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/shared/eventList/eventList.html
- imports/ui/shared/eventList/eventList.js
- imports/ui/shared/eventList/eventList.scss
- imports/ui/shared/flagItem/flagItem.html
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/learningResourceList/learningResourceList.js
- imports/ui/shared/learningResourceList/learningResourceList.scss
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/projectList/projectList.js
- imports/ui/shared/projectList/projectList.scss
- imports/ui/shared/researchList/researchList.html
- imports/ui/shared/researchList/researchList.js
- imports/ui/shared/researchList/researchList.scss
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/shared/socialResourceList/socialResourceList.scss
- imports/ui/shared/warningList/warningList.html
- imports/ui/shared/warningList/warningList.js
- imports/ui/shared/warningList/warningList.scss
Solution : 
1. Limit on title is removed as it already has 90 char limit
2. Summary limit increased to 100
3. Edit and Delete moved into ellipsis to make more space for title
> Problem: Card title & description is limited #387

- imports/ui/layouts/body/body.html
Solution : Extra menu layout on mobile removed
> Problem: weird menu layout on mobile #394

- imports/ui/shared/projectList/projectList.html
> problem: missing '{'

- imports/startup/client/routes.js
soluiton: add a filter to the routes related to the forms that triggers a check on login.
this solves issue #393
> problem: logged out users can still access forms (issue #393)

- imports/ui/shared/eventList/eventList.scss
- imports/ui/shared/learningResourceList/learningResourceList.scss
- imports/ui/shared/projectList/projectList.scss
- imports/ui/shared/researchList/researchList.scss
- imports/ui/shared/socialResourceList/socialResourceList.scss
- imports/ui/shared/warningList/warningList.scss
Solution :
Fixed height css removed
Top space added on card title
Fixes for #404 & #406
>  Problem: Card content is out of box and spacing issue with title #404 & #406

- .meteor/packages
- .meteor/versions
- imports/api/events/server/publications.js
- imports/api/learn/server/publications.js
- imports/api/projects/server/publications.js
- imports/api/research/server/publications.js
- imports/api/search/search.js
- imports/api/search/server/publications.js
- imports/api/socialResources/server/publications.js
- imports/api/warnings/server/publications.js
- imports/startup/client/routes.js
- imports/startup/server/register-api.js
- imports/ui/pages/search/search.html
- imports/ui/pages/search/search.js
- imports/ui/pages/search/search.scss
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- package-lock.json
- package.json
solution: build a global search page for all component of the site #270
> problem: unable to search

- imports/api/research/methods.js
- imports/api/research/methods.test.js
- imports/ui/pages/research/researchForm.html
- imports/ui/pages/research/researchForm.js
- imports/ui/pages/research/researchForm.scss
- imports/ui/pages/research/viewResearch.html
- imports/ui/shared/researchList/researchList.html
Solution:
Added links to research
Added UI to researchForm to add-remove-edit links
Updated UI to show links in viewResearch
Updated UI in researchList to show links
> Problem: Research paper source link is missing#377

- imports/ui/pages/research/researchForm.html
Solution: Added pdf error feedback area
> Problem: No error if PDF file is not selected #408

- imports/ui/pages/research/researchForm.html
- imports/ui/pages/research/researchForm.js
Solution: Fixed deletion logic
> Problem research link trash deletes wrong url #417

- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: adding active class if the current route name is the same as the url it links to
> Problem: no active class on side menu #397

- imports/ui/pages/tag/tag.html
- imports/ui/pages/tag/tag.js
Solution: Added conditionals to show titles, also had to move where we fetch results
> Problem: weird titles shown in tag search #389

- imports/api/warnings/methods.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/moderator/candidates/candidates.ui-test.js
- imports/ui/pages/projects/projects.ui-test.js
- imports/ui/pages/research/research.ui-test.js
- imports/ui/pages/warnings/warnings.ui-test.js
Solution: Fix failing client side tests.
> Problem: Tests are failing (#398)

- imports/ui/pages/userProfile/viewProfile.html
- imports/ui/shared/uploader/uploader.js
Soultion: If error in response then change button to Upload. #410
> Problem: [New Research] Upload PDF button rotating after error

- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/research/researchForm.js
- imports/ui/pages/warnings/warningForm.js
Solution : Is invalid class removed on key press on each input fields
> Problem: Error msg exist after enter value #411

- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/viewProfile.html
Solution : Moderator badge and rank added on user profile
> Problem: mod and user status not on profile #400

- imports/ui/pages/addNewModal/addNewModal.scss
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.scss
Solution : UI-UX updated for add new cta
Another related problem : 
Problem: clicking on outside text (on coloured link) closes the modal
Solution : Display changed to block on link items on add new modal
>  Problem: new button takes up too much space #402

- imports/ui/pages/search/search.html
- imports/ui/pages/search/search.js
solution: add awesome filters #430
> problem: unable to filter search

- imports/ui/pages/userProfile/viewProfile.html
- package-lock.json
Solution: changed the field name headline to field in the anchor tag #432
> Problem: invalid project & research link on view profile #432

- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/projects/viewProject.html
- imports/ui/shared/projectList/projectList.html
- imports/ui/shared/researchList/researchList.html
- imports/ui/shared/socialResourceList/socialResourceList.html
- imports/ui/stylesheets/_custom.scss
Solution: In HTML I have added target="_blank" in tag
> Problem: [Projects] GitHub and WebSite URL should be open in new tab #438

- imports/api/faq/faq.js
- imports/api/faq/methods.js
- imports/api/faq/server/publications.js
- imports/startup/both/routes.js
- imports/startup/client/index.js
- imports/startup/server/register-api.js
- imports/ui/pages/faq/faq.html
- imports/ui/pages/faq/faq.js
- imports/ui/pages/faq/faqForm.html
- imports/ui/pages/faq/faqForm.js
- imports/ui/shared/header/header.html
- imports/ui/shared/sidebar/sidebar.html
- package-lock.json
> Problem: FAQ page is missing #428

- imports/startup/client/routes.js
- imports/ui/layouts/body/body.html
- imports/ui/layouts/body/body.js
- imports/ui/layouts/body/body.scss
solution: added breadcrumbs for better UX #287
> problem: no breadcrumbs

- imports/ui/layouts/body/body.html
- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/faq/faqForm.html
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/warningForm.html
Solution: Remove Extra breadcrumbs bar and update existing from common places
> problem: extra bar for breadcrumbs is clumsy #448

- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/shared/learningResourceList/learningResourceList.html
- imports/ui/shared/learningResourceList/learningResourceList.js
Solution : Difficulty level added on learning content
> Problem: No difficulty level on learn #282 & #283

- imports/ui/pages/moderator/candidates/candidates.html
Solution : Hyphen replaced with semi-colon
> Problem: confused symbol for Moderator scores #449

- imports/ui/pages/moderator/flagged/flaggedItems.js
Solution : URL updated for scams
> Problem: Reported from scams link not working #453

- .meteor/packages
- imports/api/events/methods.js
- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/shared/eventList/eventList.html
- package-lock.json
- package.json
Solution: Save event times in UTC format in the mongo database and parse them correctly on the client depending on the event location timezone. Use a timezone API provider to determine the timezone of a location. Saving times in UTC preserves the ability to sort events by date correctly.
> Problem: Event time zone can easily be incorrect (#443)

- imports/ui/layouts/body/body.html
solution: Remove LI HTML tag from HTML
> problem: breadcrumb UI is weird #460

- imports/ui/pages/tag/tag.html
Solution : Layout updated for to be more a like in home page
> Problem : Tag search has different layout #464

- imports/ui/pages/community/socialResources.js
- imports/ui/pages/learn/learn.js
- imports/ui/pages/projects/projects.js
- imports/ui/pages/research/research.js
- imports/ui/pages/tag/tag.js
- imports/ui/pages/warnings/warnings.js
Solution: attached same handlers to blur as well
> Problem: "copy and paste" in searchbar #445

- imports/startup/both/routes.js
- imports/ui/stylesheets/_custom.scss
Solution: Remove view and based on find query update with headline
> Problem: "view" used in breadcrumbs #461

- imports/ui/pages/comments/commentBody.html
- imports/ui/pages/comments/commentBody.js
Solution: Added a 'Show replies' and a 'Show less' button and made listing child comments optional
> Problem: Replys in comment not optional #468

- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/viewProfile.html
Solution: Added a url pointing to the resource the comment was on
> Problem: missing link for comments in profile #471

- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/userProfile/viewProfile.html
solution: Add details about learning resource, research paper, community & events created user
> problem: missing details on user profile #477

- README.md
Solution: Send this test PR to see if the tests will be activated after modify settings.
> Problem: Tests running before merging is annoying (#476)

- client/head.html
- imports/api/config/server/publications.js
- imports/startup/both/routes.js
- imports/startup/server/startup.js
- imports/ui/pages/events/eventForm.js
Solution: Load the key for Google Maps API from `Config` collection. Only load the Google Maps API script on the events form page to prevent unnecessary loading. Fix a small bug with breadcrumbs.
> Problem: Google maps API credentials not fetched from mongo (#465)

- imports/ui/pages/userProfile/viewProfile.html
Solution : Font size of about content updated
> Problem:[/profile] Title smaller than content #472

- imports/ui/pages/moderator/candidates/candidates.html
- imports/ui/pages/moderator/changes/changes.html
- imports/ui/pages/moderator/pardon/pardon.html
Solution: Adds consistent UI to all the noderate routes in the app.
> Problem: inconsistent ui for moderate routes #487

- imports/api/comments/methods.js
- imports/api/notifications/methods.js
- imports/ui/pages/comments/commentBody.js
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/events/viewEvent.js
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/notifications/notifications.html
- imports/ui/pages/notifications/notifications.js
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/research/viewResearch.js
- imports/ui/pages/warnings/viewWarning.js
Solution : Notifications added for all contents
> Problem : No user notification #482

- imports/ui/pages/search/search.html
- imports/ui/pages/search/search.js
- imports/ui/pages/search/search.scss
Solution: Updated how we filter results, stored filters in queryparam, updated UI
> Problem: search resets filters on refresh #475

- imports/startup/client/index.js
- imports/ui/pages/community/socialResources.html
- imports/ui/pages/community/socialResources.js
- imports/ui/pages/learn/learn.html
- imports/ui/pages/learn/learn.js
- imports/ui/pages/projects/projects.html
- imports/ui/pages/projects/projects.js
- imports/ui/pages/research/research.html
- imports/ui/pages/research/research.js
- imports/ui/pages/warnings/warnings.html
- imports/ui/pages/warnings/warnings.js
- imports/ui/shared/searchBar/searchBar.html
- imports/ui/shared/searchBar/searchBar.js
- imports/ui/shared/searchBar/searchBar.scss
Solution: Added result count text, moved to common search bar component, added an advanced search link
> problem: search bar result isn't clear enough #444

- imports/ui/pages/search/search.html
- imports/ui/pages/search/search.js
- imports/ui/shared/searchBar/searchBar.html
- imports/ui/shared/searchBar/searchBar.js
Solution:
Updated search page to use the common searchBar component for entry
Updated searchBar to only optionally display the advanced search link and to take external updates to the search input
> Problem: search page looks different #495

- imports/api/comments/methods.test.js
> Problem: comments tests are failing #501

- imports/api/projects/methods.js
- imports/ui/pages/moderator/flagged/flaggedItems.ui-test.js
Solution: Implemented a generateTestFlaggedProject that insert projects with flags already set
> Problem: flagged items ui tests failing #506

- imports/ui/shared/searchBar/searchBar.js
Solution: when user get search terms then we have to check its undefined or not.
> Problem: [Projects] advance search show "undefined" #510

- imports/startup/client/index.js
- imports/ui/pages/comments/commentBody.html
- imports/ui/pages/comments/commentBody.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/shared/commentForm/commentForm.html
- imports/ui/shared/commentForm/commentForm.js
Solution: Extracted common commentForm component, Updated UI to use new component
> Problem: comment form code is duplicated #508

- imports/ui/pages/events/events.html
- imports/ui/pages/events/events.js
- imports/ui/pages/projects/projects.js
- imports/ui/pages/tag/tag.js
Solution: Apply where dependacies of event search bar.
> Problem: [Events] Search and advance search not exist #511

- imports/ui/shared/sidebar/sidebar.js
solution: only close side menu on mobile devices #521
> problem: side menu open on mobile

- imports/startup/client/index.js
- imports/startup/server/startup.js
- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/community/socialResourceForm.js
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/projects/projectForm.js
- imports/ui/pages/projects/projects.scss
- imports/ui/shared/tagInput/tagInput.html
- imports/ui/shared/tagInput/tagInput.js
solution: Adds a tagInput component to reuse the code & reduce code duplication in the forms
> problem: code duplication for tags in forms #518

- imports/startup/both/routes.js
- imports/ui/pages/login/login.js
Solution: import package in client condition
> Problem: [Home] '+ Add new content' popup gives error & no redirect #530

- imports/ui/pages/home/home.scss
- imports/ui/shared/searchResults/searchResults.html
Solution: Update div and remove btn class from tag.
> Problem: [ Home ] +Add New Content text hide behind #535

- imports/ui/stylesheets/_custom.scss
Solution: Set min height to window height
> Problem: [Mobile] black shadow display in content height #538

- imports/api/socialResources/methods.js
- imports/ui/pages/community/socialResources.ui-test.js
> Problem: no tests for community page #515

- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/ui/pages/community/socialResources.ui-test.js
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/shared/socialResourceCard/socialResourceCard.html
- imports/ui/shared/socialResourceCard/socialResourceCard.js
Solution: Added flagging to social resources
> Problem: can't flag community resources #545

- imports/api/learn/methods.js
- imports/api/projects/methods.js
- imports/api/socialResources/methods.js
- imports/ui/shared/tagInput/tagInput.js
Solution: unmention the tags when they are removed in edit mode
> Problem:tag mention not decreased if tag is removed in edit #527

- imports/ui/shared/searchResults/searchResults.html
- imports/ui/shared/searchResults/searchResults.js
solution: Adds sort by title to the search component
> problem: [/] cards are sorted in a boring way #442

- imports/api/user/users.js
Solution : Send email with verification link on user signup
> Problem: no email verification for new users #550

- imports/startup/client/config.js
- imports/ui/shared/sidebar/sidebar.js
Solution: set toggle sub menu working, for mobile - prevent sidebar hide on main item click
> Problem: [Side menu] Moderator menu hide show not working #555

- imports/ui/shared/header/header.scss
Solution: Remove unnecessary space and set header item in one line
> Problem: [Header] Not in one line in small desktop/laptop #561

- imports/ui/pages/home/home.js
- imports/ui/shared/searchResults/searchResults.js
Solution: added an optional filter
> problem: past events are shown on home route #557

- README.md
Solution : Email setup instruction added on ReadME
> Problem : Email setup instruction not available

- imports/ui/shared/userNameDisplay/userNameDisplay.html
- imports/ui/shared/userNameDisplay/userNameDisplay.js
Solution: Removed unnecessary logging
> Problem: usernamedisplay spams console #570

- i18n/events.en.i18n.json
- i18n/research.en.i18n.json
- imports/api/user/methods.js
- imports/startup/client/index.js
- imports/ui/pages/community/socialResources.ui-test.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/events/viewEvent.js
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/projects/projects.ui-test.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/research/research.ui-test.js
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/research/viewResearch.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/pages/warnings/warnings.ui-test.js
- imports/ui/shared/commentArea/commentArea.app-test.js
- imports/ui/shared/commentArea/commentArea.html
- imports/ui/shared/commentArea/commentArea.js
- imports/ui/shared/commentCard/commentCard.html
- imports/ui/shared/commentCard/commentCard.js
- imports/ui/shared/commentForm/commentForm.html
- imports/ui/shared/commentForm/commentForm.js
- imports/ui/uiUnitTestUtils.js
Solution:
Moved commentBody from pages into shared next to other comment related components
Added a new commentArea component that is now used across pages
Updated content pages (and tests) to use the new component
Added a new type of test to test commentArea in relative separation
Added new test utils for these type of tests
> Problem: comment ui is inconsistent #554

- imports/ui/helpers/handlebars-helpers.js
- imports/ui/pages/events/eventForm.js
- imports/ui/pages/learn/learnForm.js
Solution: added sanitize to "marked" options both when displaying content ourselves and as simplemde generates previews
> problem: security vulnerability found #569

- imports/ui/pages/login/login.html
- imports/ui/pages/login/login.js
- imports/ui/pages/signup/signup.html
- imports/ui/pages/signup/signup.js
Solution: Fixed translation string keys on login/signup pages
> Problem: login page not translated properly #575

- imports/ui/pages/events/eventForm.js
Solution: Setting the datepicker when the event loads.
> Problem: event date is not set when editing #577

- imports/startup/client/index.js
- imports/ui/shared/header/header.js
Solution: saving ui language in sessionStorage
> Problem: language choice is lost on refresh #579

- i18n/shared.en.i18n.json
- imports/startup/client/index.js
- imports/ui/layouts/body/body.html
- imports/ui/shared/footer/footer.html
- imports/ui/shared/footer/footer.js
- imports/ui/shared/footer/footer.scss
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
Solution:
Added footer area
Moved language chooser to footer
Please review footer text before merging!
> Problem: language chooser is too big #581

- i18n/user.en.i18n.json
- imports/api/user/methods.js
- imports/startup/client/index.js
- imports/ui/pages/login/login.js
- imports/ui/pages/signup/signup.js
- imports/ui/pages/userProfile/editProfile.html
- imports/ui/pages/userProfile/userProfile.js
Solution:
Added a language field to profile
Saving current UI language on signup as default in profile
Setting language after login
> Problem: users can't save a default language #583

- imports/ui/layouts/body/body.scss
- imports/ui/shared/footer/footer.scss
> Problem: footer placement not always good #585

- imports/ui/shared/commentCard/commentCard.html
- imports/ui/shared/commentCard/commentCard.js
- imports/ui/shared/commentForm/commentForm.html
- imports/ui/stylesheets/_custom.scss
Solution: remove too much spaces, threads are followed, set buttons/action size smaller
> Problem: comment ui is clumsy #573

- imports/ui/shared/commentArea/commentArea.html
- imports/ui/shared/commentCard/commentCard.html
- imports/ui/shared/commentCard/commentCard.js
- imports/ui/shared/commentCard/commentCard.scss
- imports/ui/stylesheets/_custom.scss
Solution:
Moved scss into component scss from general custom.scss
Reworked scss to make the comment ui more compact
Moved reply form into the replies div
Auto-opening replies when clicking reply
Showing reply count in hide/show replies
> Problem: Comment threads can be confusing #588

- imports/api/events/methods.test.js
- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/api/projects/methods.test.js
- imports/api/research/methods.test.js
- imports/api/socialResources/methods.test.js
- imports/api/warnings/methods.test.js
- imports/ui/shared/commentArea/commentArea.app-test.js
Solution: Updated&added tests + fixed small error in learn API
> Problem: translations are not tested on apis #591

- imports/api/socialResources/socialResources.js
Solution: changes the field for slug generation to NAME
> Problem: social resource slugs are not generated properly #594

- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/api/projects/methods.js
- imports/api/projects/methods.test.js
- imports/api/research/methods.js
- imports/api/research/methods.test.js
- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/api/translationGroups/methods.js
- imports/api/translationGroups/methods.test.js
- imports/api/warnings/methods.js
- imports/api/warnings/methods.test.js
Solution:
Added updateTranslationSlug to translation group API
Updating translation slugs on edit
Updated tests to check slug update
Fixed test regression from #596
> Problem: translation slugs are not updated #597

- imports/ui/shared/footer/footer.html
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/sidebar/sidebar.html
- imports/ui/shared/sidebar/sidebar.js
Solution: Adds language switcher to side bar & user dropdown menu
> Problem: language switcher is hard to find #601

- imports/ui/shared/searchResults/searchResults.js
Solution: solve excepetion for old data when sort by title
> Problem: [Home] Sorting with title is not working #604

- imports/api/translationGroups/server/publications.js
- imports/api/user/methods.js
- imports/ui/pages/community/socialResources.ui-test.js
- imports/ui/pages/community/viewSocialResource.html
- imports/ui/pages/community/viewSocialResource.js
- imports/ui/pages/events/events.ui-test.js
- imports/ui/pages/events/viewEvent.html
- imports/ui/pages/events/viewEvent.js
- imports/ui/pages/home/home.js
- imports/ui/pages/learn/learn.ui-test.js
- imports/ui/pages/learn/learnForm.js
- imports/ui/pages/learn/viewLearn.html
- imports/ui/pages/learn/viewLearn.js
- imports/ui/pages/moderator/flagged/flaggedItems.ui-test.js
- imports/ui/pages/projects/projects.ui-test.js
- imports/ui/pages/projects/viewProject.html
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/research/research.ui-test.js
- imports/ui/pages/research/researchForm.js
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/research/viewResearch.js
- imports/ui/pages/search/search.ui-test.js
- imports/ui/pages/signup/signup.js
- imports/ui/pages/warnings/viewWarning.html
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/pages/warnings/warnings.ui-test.js
- imports/ui/shared/commentArea/commentArea.app-test.js
- imports/ui/shared/commentCard/commentCard.html
- imports/ui/shared/commentForm/commentForm.js
- imports/ui/uiTestUtils.js
Solution:
Added test utilities
Added basic tests for translating content
Fixed other tests
Small additional fixes based on test errors
> Problem: translations are not ui tested #593

- i18n/breadcrumbs.en.i18n.json
- i18n/moderator.en.i18n.json
- i18n/shared.en.i18n.json
- i18n/shared.sr.i18n.json
- i18n/translations.en.i18n.json
- imports/api/translations/methods.js
- imports/api/translations/server/publications.js
- imports/api/translations/server/startup.js
- imports/api/translations/translations.js
- imports/startup/both/routes.js
- imports/startup/server/register-api.js
- imports/ui/pages/moderator/translations/translation.html
- imports/ui/pages/moderator/translations/translation.js
- imports/ui/pages/moderator/translations/translations.html
- imports/ui/pages/moderator/translations/translations.js
- imports/ui/pages/translations/translations.html
- imports/ui/pages/translations/translations.js
- imports/ui/shared/sidebar/sidebar.html
- package-lock.json
- package.json
Solution: Recycle most of the Blockrazor system for adding new languages and translations and adapt it to this project.
> Problem: Users cannot add new languages (#600)

- imports/ui/shared/searchResults/searchResults.js
Solution: return keyword is missing, add it and sorting is working
> Problem: [Home] Sorting with title no exception but not working #615

- imports/ui/shared/footer/footer.scss
Solution: Adjust width for footer when menu is open
> Problem: [Common] on sidebar open scroll horizontal showing #616

- imports/api/user/methods.js
- imports/ui/pages/home/home.js
- imports/ui/pages/learn/learn.js
- imports/ui/pages/projects/projects.js
- imports/ui/pages/research/research.js
- imports/ui/pages/search/search.js
- imports/ui/pages/search/search.ui-test.js
- imports/ui/pages/userProfile/editProfile.html
- imports/ui/pages/userProfile/userProfile.js
- imports/ui/pages/warnings/warnings.js
Solution:
- Added contentLanguages optional field into profile
- Added UI into edit profile to allow setting it
- Added contentLanguages as filter in every page where we list content without allowing to filter for languages
- Setting filters by default from this field if present
> Problem: users can't save default languages #612

- imports/ui/shared/searchResults/searchResults.js
Solution: fixes the incorrect field of social resources used for sort
> Problem: sort by title not working on pages #608

- imports/api/translations/methods.js
- imports/api/translations/methods.test.js
- imports/ui/pages/translations/translations.ui-test.js
Solution: Add client-side and server-side tests.
> Problem: Mechanism for adding new translations is not tested (#607)

- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/projects/projectForm.html
- imports/ui/pages/research/researchForm.html
- imports/ui/pages/warnings/warningForm.html
Solution: Add class to match form UI style
> Problem: [Form] Language input not match form UI #620

- i18n/shared.en.i18n.json
- imports/modules/flagDialog.js
- imports/startup/both/routes.js
- imports/ui/helpers/loggedInSWAL.js
- imports/ui/layouts/body/body.js
- imports/ui/pages/faq/faq.js
- imports/ui/pages/login/login.js
- imports/ui/pages/projects/viewProject.js
- imports/ui/pages/research/research.js
- imports/ui/pages/warnings/viewWarning.js
- imports/ui/shared/commentCard/commentCard.js
- imports/ui/shared/commentForm/commentForm.js
- imports/ui/shared/eventCard/eventCard.js
- imports/ui/shared/learningResourceCard/learningResourceCard.js
- imports/ui/shared/projectCard/projectCard.js
- imports/ui/shared/researchCard/researchCard.js
- imports/ui/shared/socialResourceCard/socialResourceCard.js
- imports/ui/shared/warningCard/warningCard.js
Solution:
Removed catch-all redirect
Added special log in modal
Moved to use new redirection modal where the modal makes an action that needs the user to log in
Added route guard for every /new /edit /translate
Fixed redirection after login
> Problem: redirecting to login in many places #613

- i18n/messages.en.i18n.json
- i18n/translations.en.i18n.json
- imports/api/translations/methods.js
- imports/api/translations/server/publications.js
- imports/api/translations/server/startup.js
- imports/ui/pages/translations/translations.html
- imports/ui/pages/translations/translations.js
Solution: Allow users to add new languages to the language selector on the translations page.
> Problem: Users can't actually add new languages to system (#629)

- imports/ui/shared/sidebar/sidebar.html
Solution: Seperate each side menu item, so hover will apply for one item
> Problem: [Side Menu] mouse over on item it expand all items #632

- imports/ui/pages/translations/translations.html
Solutions: set page content in same container as it follow in other pages
> Problem: [Translate Page] content width not match site layout #634

- .meteor/packages
- .meteor/versions
- imports/startup/server/startup.js
Solution: Integrate Kadira to gain more insight into what's really causing slow mongo payloads.
> Problem: Initial mongo payload is slow (#631)

- imports/ui/pages/learn/learnForm.js
solution: Fixes the logic for preselecting the radio button in edit mode of learn form
> problem: can't edit Difficulty level of "learning resource" #640

- imports/ui/helpers/handlebars-helpers.js
solution: Fix view logic by not converting iframe html to text & leaving it unsanetized
> problem: can't show youtube video in "learning resource" #639

- imports/ui/stylesheets/bootstrap/_bootstrap.scss
- package-lock.json
- package.json
Solution: Updated bootstrap to ^4.2.1
> Problem: bootstrap should be updated #643

- imports/ui/shared/footer/footer.scss
Solution: set width according to sidemenu
> Problem: [Footer] When side menu in small size, extra space #646

- imports/ui/pages/userProfile/userProfile.scss
- imports/ui/pages/userProfile/viewProfile.html
Solution: Set responsive view for tabs
> Problem: [Profile] User's Activity tabs need to set in Small screen #648

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
Solution : Smaller logo added for smaller screens
> Problem : No logo on mobile #651

- imports/api/stats/methods.js
- imports/api/stats/server/startup.js
- imports/ui/pages/home/home.html
- imports/ui/pages/home/home.js
Solution :  Total projects, learning resources and research papers added instead of total users, new users and content last month.
> Problem: activity looks boring #650

- imports/api/events/methods.js
- imports/api/projects/methods.js
- imports/api/research/methods.js
- imports/api/socialResources/methods.js
Solution : Simple schema regex added for email validation on schema
> Problem : No validation for urls across site #654

- imports/api/user/methods.js
- imports/ui/layouts/body/body.html
- imports/ui/layouts/body/body.js
Solution : Waring for not verified users added with resend verification email
> Problem : Can't resend verification email #656

- imports/ui/pages/tag/tag.html
- imports/ui/pages/tag/tag.js
Solution: Called Proper template for display tag result
> Problem: [Tag Search] no tag search is working #659

- i18n/comments.ja.i18n.json
Solution: Add Japanese translation to comments
> Problem: comments in Japanese

- i18n/events.ja.i18n.json
Solution: add Japanese translation to events.
> Problem: events not in Japanese

- i18n/faq.ja.i18n.json
Solution: add Japanese translation in faq
> Problem: faq not in Japanese

- i18n/learn.ja.i18n.json
Solution: add Japanese translation to learn
> Problem: learn not in Japanese

- i18n/moderator.ja.i18n.json
Solution: Add Japanese translation to moderator.
> Problem: moderator not in Japanese

- i18n/notifications.ja.i18n.json
Solution: Add Japanese translation to notifications
> Problem: notifications not in Japanese

- i18n/research.ja.i18n.json
Solution: add Japanese translation to research.
> Problem: research not in Japanese

- i18n/search.ja.i18n.json
Solution: add Japanese translation to search.
> Problem: search not in Japanese.

- i18n/community.ja.i18n.json
Solutions: fixed translations.
> Problem: some translations were weird

- i18n/faq.ja.i18n.json
> Problem: some translations were weird.

- i18n/user.ja.i18n.json
> problem: incorrect JSON format

- i18n/research.ja.i18n.json
> Problem: Weird translations

- imports/api/events/methods.js
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/events/eventForm.js
Solution : Google maps removed from location bar and timezone
> Problem: google maps API is killing things #712

- imports/ui/pages/home/home.js
Solution : Content Language set automatically on chnage language
> Problem: content lang isn't set automatically #714

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/header/loginModal/login.html
- imports/ui/shared/header/loginModal/login.js
- imports/ui/shared/header/loginModal/login.scss
Solution : Login and signup moved to modal
> Problem : Sign in and sign up pages bad ux #718

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/header/loginModal/login.html
- imports/ui/shared/header/loginModal/login.js
Solution: Set Form Action and on error do not hide popup, and reset form after submitted.
> Problem: [Login] Popup Form submit events not working proper #728

- imports/api/events/events.js
- imports/api/learn/learn.js
- imports/api/projects/projects.js
- imports/api/research/research.js
- imports/api/socialResources/socialResources.js
- imports/api/warnings/warnings.js
Solution: Update slug for each translate items so redirect works
> Problem: [View Page] Action placed wrong or Translation not working #727

- imports/ui/shared/commentForm/commentForm.js
- imports/ui/shared/header/loginModal/login.js
Solution: Remove confirm popup and open direct login popup
> Problem: [Comment] it redirect to login page instead open popup #731

- imports/ui/pages/addNewModal/addNewModal.js
Solution: open modal for login and after login redirect to add form
> Problem: [Add Content] if not logged in, it open add popup #733

- imports/ui/shared/flagItem/flagItem.scss
Solution: apply css to overlay inline css
> Problem:[Search] Option menu on card is not working #735

- imports/startup/both/routes.js
- imports/ui/shared/header/loginModal/login.js
Solution: If user not logged in then open login modal, and after login redirect to form page
> Problem: [Add Button] if not logged in, it redirect to login page #736

- imports/ui/helpers/loggedInSWAL.js
Solution: It should open login popup
> Problem: [Report] report ask login, instead of open login popup #740

- AUTHORS
- README.md
solution: Add a reminder in Readme.
> problem: Reminder missing

- imports/startup/both/routes.js
Solution: page position always set on top when go to other page
> Problem: [Page] Go to next page, scroll position not on top

- imports/startup/both/routes.js
Solution: if not login, open popup and after logged in redirect to translate page
> Problem: [Scams] Add translation sometimes not open login model #747

- imports/ui/pages/translations/translations.html
- imports/ui/pages/translations/translations.js
- imports/ui/shared/footer/footer.js
- imports/ui/shared/sidebar/sidebar.js
Solution: Open Add Form on select add option, also once change lang in page, hide add form
> Problem: [Add Language] Not Open Form from header or sidebar #749

- imports/ui/pages/faq/faq.html
- imports/ui/shared/searchResults/searchResults.html
- imports/ui/shared/searchResults/searchResults.js
Solution: Add spinner until data is not ready
> Problem: [Loading] no loading when data not ready #759

- imports/ui/pages/community/socialResourceForm.html
- imports/ui/pages/events/eventForm.html
- imports/ui/pages/learn/learnForm.html
- imports/ui/pages/warnings/warningForm.html
Solution: Add space between captcha and input
> Problem: [From] some form with space captcha and some not #757

- imports/ui/stylesheets/_custom.scss
Solution: set pointer using css
> Problem: [Card] not cursor pointer if website value is null #751

- imports/ui/stylesheets/_custom.scss
Solution: In small view set content height more
> Problem: [Footer] in small screen footer over content #753

- imports/ui/pages/userProfile/userProfile.js
Solution: Check emails is exists or not
> Problem: [Profile] Exception for emails if not exists #755

- imports/api/events/events.js
- imports/api/events/methods.js
- imports/api/learn/learn.js
- imports/api/learn/methods.js
- imports/api/projects/methods.js
- imports/api/projects/projects.js
- imports/api/research/methods.js
- imports/api/research/research.js
- imports/api/socialResources/methods.js
- imports/api/socialResources/socialResources.js
- imports/api/warnings/methods.js
- imports/api/warnings/warnings.js
- package-lock.json
- package.json
Solution : slugs are created from content heading and translated to english for non-english post
> Problem : content links are broken #717

- imports/api/user/users.js
Solution : Email Templates added for verify email, reset password and enrollment email
> Problem : Welcome email is too boring #657

- imports/ui/pages/translations/translations.js
Solution: When Add Language is active only then form is displaying
> Problem: [Language] Add language open form and change to 'Deutsch' #764

- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/api/projects/methods.test.js
- imports/api/research/methods.js
- imports/api/research/methods.test.js
- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/api/warnings/methods.test.js
Solution: Fixed tests + slug generation issue that blocked adding events, learning resources, research, social resources
> Problem : Tests are failing #661

- imports/startup/both/routes.js
Solution: Added login filter for notification page and fix open login popup issue
> Problem: [Notification] no need to show it until user not log in #766

- .meteor/packages
- .meteor/versions
- imports/api/research/methods.js
- imports/api/research/methods.test.js
- imports/api/research/research.js
- imports/api/research/server/publications.js
- imports/ui/pages/research/researchForm.html
- imports/ui/pages/research/researchForm.js
- imports/ui/pages/research/viewResearch.html
- imports/ui/pages/research/viewResearch.js
- imports/ui/shared/progressiveUploader/uploader.html
- imports/ui/shared/progressiveUploader/uploader.js
- imports/ui/shared/progressiveUploader/uploader.scss
Solution: Implemented a new uploader component using Meteor-Files and refactored research to use it
> Problem: No progress on file upload #771

- package-lock.json
- package.json
Solution: installed&saved missing package
> Problem: cannot find package mkdirp #775

- imports/api/events/methods.js
- imports/api/events/methods.test.js
- imports/api/learn/methods.js
- imports/api/learn/methods.test.js
- imports/api/projects/methods.js
- imports/api/projects/methods.test.js
- imports/api/research/methods.js
- imports/api/research/methods.test.js
- imports/api/socialResources/methods.js
- imports/api/socialResources/methods.test.js
- imports/api/warnings/methods.js
- imports/api/warnings/methods.test.js
- imports/modules/flagDialog.js
- imports/modules/flagDialog.scss
- imports/ui/pages/moderator/flagged/flaggedItems.html
- imports/ui/pages/moderator/flagged/flaggedItems.js
- imports/ui/pages/moderator/flagged/flaggedItems.scss
Solution :
- SWAL popup updated
- Additional options are added for reason for reporting
- Optional text area added for remarks
- Test cases updated
- Schemas updated for new field (remark)
- [ moderator/flagged ] page ui updated
> Problem: items cannot be deprecated #772

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
Solution: Set all items in aligned and icon size updated
> Problem: Header not align after logged in, search in small device #770

- imports/ui/pages/research/researchForm.js
Solution: Fixed display of pdfs + formatting by prettier
> Problem: uploading a new pdf shows both #787

- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.scss
Solution: set element aligned and for username set max width and ... for long name
> Problem: [Header] For Laptop screen break to new line #785

- imports/ui/layouts/body/body.js
- imports/ui/shared/header/header.html
- imports/ui/shared/header/header.js
- imports/ui/shared/header/header.scss
Solution: change search hide and clear text functional
> Problem: [Search] textbox should not hide where not empty #790

- imports/modules/flagDialog.js
Solution: if user not logged in, first open model to login
> Problem: [Report] After submit error message not proper #792

- imports/startup/both/routes.js
- imports/ui/stylesheets/not-found.less
Solution: Set not found page, as per layout and set responsive view of it
> Problem: [404] header is hide so white space in top #795

- imports/api/events/methods.js
- imports/api/learn/methods.js
- imports/api/projects/methods.js
- imports/api/research/methods.js
- imports/api/socialResources/methods.js
- imports/api/twitter.js
- imports/api/warnings/methods.js
- package-lock.json
- package.json
Solution:
- Added a new dependency to handle twitter
- Loading config from db
- Added respective calls to content creation methods
> problem: twitter users can't follow updates #793

- .meteor/packages
- imports/startup/server/index.js
- imports/startup/server/meta.js
Solution:
- We render meta tags for certain paths
- Text/img will have to be updated, we need to check in context (and FB would not cooperate)
> problem: social media users cannot preview #798

- imports/ui/shared/searchResults/searchResults.html
- imports/ui/shared/searchResults/searchResults.js
Solution: Update sort code and icon for sorting
> Problem: [Sorting] both sorting not apply at same time #797

- imports/ui/shared/header/loginModal/login.html
- imports/ui/shared/header/loginModal/login.js
solution: update facebook login button
> problem: facebook button non-compliant

- imports/api/socialResources/methods.js
Solution: Rename the incorrect variable
solved issue #805
> Problem: Problem: Exception while invoking method 'addSocialResource'

- imports/ui/shared/flagItem/flagItem.scss
- imports/ui/shared/header/header.scss
Solution: Set content in screen when option menu open
> Problem: [Card] In small screen options cut in screen #810

- imports/ui/shared/searchBar/searchBar.js
Solution: not redirect to other page
> Problem: [Search] Advance page 'x' should not redirect to home #814

- imports/ui/shared/header/header.scss
Solution: set icon color common and match header with same color
> Problem: [Header] in tablet/mobile top icons in two color #820

- imports/ui/shared/header/loginModal/login.html
- imports/ui/shared/header/loginModal/login.js
Solution: revert my previous commit
> problem: facebook logic is broken

- i18n/sign.en.i18n.json
- imports/ui/shared/header/loginModal/login.html
Solution: Modify the facebook button
> Problem: Login button violate Facebook compliance
